# Generated by Django 5.2.4 on 2025-07-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="play",
            name="duration",
        ),
    ]
